name: build-on-ubuntu

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from git
      uses: actions/checkout@v2
      with: 
        submodules: 'true'
    - name: Cache multiple paths
      uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
          ~/perl5
        key: ${{ runner.os }}-cache3
    - name: Update apt 
      run: sudo apt update
    - name: Install apt dependencies
      run: sudo apt install -y ragel re2c dos2unix texinfo texi2html gdb curl cpanminus ccache libboost-all-dev libmodern-perl-perl libyaml-perl liblocal-lib-perl libcapture-tiny-perl libpath-tiny-perl libtest-differences-perl libtext-table-perl libdata-hexdump-perl libregexp-common-perl libclone-perl
    - name: Install perl prerequisites
      run: cpanm --local-lib=~/perl5 App::Prove Capture::Tiny::Extended CPU::Z80::Assembler Data::HexDump File::Path List::Uniq Modern::Perl Object::Tiny::RW Test::Cmd Test::Cmd::Common Test::Harness Test::HexDifferences Text::Diff Text::Table YAML::Tiny
    - name: Build binaries
      run: eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); ./build.sh -l
    - name: Build libraries
      run: eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); ./build.sh -b
    - name: Build examples
      run: eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); ./build.sh -b -l -e
    - name: Build sdcc needed for tests
      run: make BUILD_SDCC=1 BUILD_SDCC_HTTP=1 bin/z88dk-zsdcc
    - name: Build tests
      run: eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); ./build.sh -b -l -t
